queue_rules:
  - name: default
    conditions: []

pull_request_rules:
  - name: merge using the merge queue
    conditions:
      - "#files=1"
      - "author=theinfosecguy-example"
    actions:
      queue:
        name: default